# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CreateAccount.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43reateAccount.proto\x12\x04widm\"1\n\x0ePasswordSignUp\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\x0bSetUsername\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"3\n\x11NotificationToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07\x61llowed\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CreateAccount_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PASSWORDSIGNUP']._serialized_start=29
  _globals['_PASSWORDSIGNUP']._serialized_end=78
  _globals['_SETUSERNAME']._serialized_start=80
  _globals['_SETUSERNAME']._serialized_end=140
  _globals['_NOTIFICATIONTOKEN']._serialized_start=142
  _globals['_NOTIFICATIONTOKEN']._serialized_end=193
# @@protoc_insertion_point(module_scope)
