# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Vote.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nVote.proto\x12\x04widm\"\xb7\x01\n\x0bVoteMessage\x12/\n\x07message\x18\x01 \x03(\x0b\x32\x1e.widm.VoteMessage.VotesMessage\x1aw\n\x0cVotesMessage\x12\x0b\n\x03int\x18\x01 \x01(\x05\x12\x32\n\x05votes\x18\x02 \x03(\x0b\x32#.widm.VoteMessage.VotesMessage.Vote\x1a&\n\x04Vote\x12\x0e\n\x06person\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Vote_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEMESSAGE']._serialized_start=21
  _globals['_VOTEMESSAGE']._serialized_end=204
  _globals['_VOTEMESSAGE_VOTESMESSAGE']._serialized_start=85
  _globals['_VOTEMESSAGE_VOTESMESSAGE']._serialized_end=204
  _globals['_VOTEMESSAGE_VOTESMESSAGE_VOTE']._serialized_start=166
  _globals['_VOTEMESSAGE_VOTESMESSAGE_VOTE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
